"""The template against Phil Karn's wwvsim, and against real recordings.

The template's structure was read off ``gen_ticks`` in wwvsim
(github.com/ka9q/wwvsim), so these rows check the reading rather than trusting
it. Neither the replica audio nor the IQ fixtures live in this repository, so
each row skips when its input is absent -- see the module docstring in
``hf_timestd.replica`` for how to regenerate the replica.

Build note, because it cost time: wwvsim guards portaudio with ``#ifdef``, so
the ``#define USE_PORTAUDIO`` line must be DELETED rather than set to 0, and
``paths.h`` must be generated by hand. Its ``-1`` flag does not bound the
output -- bound it with ``head -c``, since one minute at 24 kHz 16-bit mono is
exactly 2,880,000 bytes.
"""

import pathlib

import numpy as np
import pytest

from hf_timestd.replica.correlate import correlate_minute

FS = 24000
DEC = 12
REPLICA = {
    "1000": pathlib.Path("/tmp/claude-1000/wwv_min.raw"),
    "1200": pathlib.Path("/tmp/claude-1000/wwvh_min.raw"),
}
FIXTURES = pathlib.Path("/home/mjh/hamsci/fixtures")
ONE_MINUTE = 60 * FS


def _decimate(x):
    n = (len(x) // DEC) * DEC
    return x[:n].reshape(-1, DEC).mean(axis=1)


def _band_env(audio, band):
    from hf_timestd.core.registration_acquirer import band_envelopes

    return _decimate(band_envelopes(audio, FS)[band].astype(np.float64))


def _replica_env(band):
    path = REPLICA[band]
    if not path.exists():
        pytest.skip(f"no replica at {path}; regenerate with wwvsim")
    pcm = np.fromfile(path, dtype=np.int16).astype(np.float64)
    if len(pcm) < ONE_MINUTE:
        pytest.skip(f"{path} holds under a minute")
    return _band_env(pcm[0:ONE_MINUTE], band)


@pytest.mark.parametrize("band", ["1000", "1200"])
def test_the_template_finds_wwvsims_own_minute_on_time(band):
    """Lag near zero and a score far above the floor, in the station's band."""
    c = correlate_minute(_replica_env(band), FS // DEC)
    assert abs(c.lag_s) < 0.005, f"lag {c.lag_s * 1e3:+.3f} ms"
    assert c.admissible
    assert c.cc_snr > 50.0


def test_wwv_and_wwvh_score_alike_because_they_share_the_structure():
    """One template serves both: the band picks the station, not this."""
    a = correlate_minute(_replica_env("1000"), FS // DEC)
    b = correlate_minute(_replica_env("1200"), FS // DEC)
    assert a.cc_snr == pytest.approx(b.cc_snr, rel=0.05)
    assert a.lag_s == pytest.approx(b.lag_s, abs=0.001)


def test_the_score_does_NOT_identify_the_station():
    """⚠ A documented LIMIT, so nobody later reads identity into this number.

    WWV read through WWVH's band still correlates strongly -- measured 371.9
    against 103.1 in its own band -- because the leakage carries the same TIME
    structure, and the score is normalised by its own noise floor. Station
    identity lives in the bands' relative ENERGY, never here.
    """
    own = correlate_minute(_replica_env("1000"), FS // DEC)
    pcm = np.fromfile(REPLICA["1000"], dtype=np.int16).astype(np.float64)
    leaked = correlate_minute(_band_env(pcm[0:ONE_MINUTE], "1200"), FS // DEC)
    assert leaked.admissible, "leakage still scores as structure"
    assert leaked.cc_snr > 0.5 * own.cc_snr


# fixture stem, channel, band, whether the channel carries usable structure
FIXTURE_ROWS = [
    ("nd-20260906", "SHARED_10000", "1000", True),
    ("nd-20260906-bad", "SHARED_10000", "1200", True),
    ("b4-20260906-day", "SHARED_10000", "1000", True),
    # ⚡ The two that made the case for this module: their fold-peak series
    # published -46.8 and -216.6 ppm, and 20/25 MHz simply was not open at ND.
    ("nd-20260906", "WWV_20000", "1000", False),
    ("nd-20260906", "WWV_25000", "1000", False),
]


def _first_minute(stem, channel):
    import json

    import zstandard

    d = FIXTURES / stem
    if not d.is_dir():
        pytest.skip(f"no fixture at {d}")
    for sc in sorted(d.glob("*.json")):
        if json.loads(sc.read_text())["channel_name"] != channel:
            continue
        binary = sc.with_suffix(".bin.zst")
        if not binary.exists():
            pytest.skip(f"{binary} absent")
        with open(binary, "rb") as fh:
            raw = (
                zstandard.ZstdDecompressor()
                .stream_reader(fh)
                .read(60 * FS * 8)
            )
        iq = np.frombuffer(raw, dtype=np.complex64)
        if len(iq) < ONE_MINUTE:
            pytest.skip(f"{binary} holds under a minute")
        amp = np.abs(iq[0:ONE_MINUTE]).astype(np.float64)
        return amp - amp.mean()
    pytest.skip(f"{stem} carries no channel {channel}")


@pytest.mark.parametrize("stem,channel,band,usable", FIXTURE_ROWS)
def test_the_score_separates_a_live_channel_from_a_dead_one(
    stem, channel, band, usable
):
    c = correlate_minute(
        _band_env(_first_minute(stem, channel), band), FS // DEC
    )
    if usable:
        assert c.admissible, f"{stem}/{channel} refused at {c.cc_snr:.1f}"
    else:
        assert not c.admissible, (
            f"{stem}/{channel} admitted at {c.cc_snr:.1f}; its fold series"
            " published a rate wrong by orders of magnitude"
        )
