# Minimal GRAPE Configuration
# This is the simplest possible configuration for GRAPE recording

[station]
callsign = "AC0G"
grid_square = "EM38ww"

[ka9q]
# Only thing you need to specify about ka9q-radio!
status_address = "bee1-hf-status.local"
auto_create_channels = true

[recorder]
data_dir = "/mnt/grape-data"

# Define what you want to record - that's it!
# Multicast addresses, ports, etc. are all discovered automatically

[[recorder.channels]]
ssrc = 2500000
frequency_hz = 2500000
description = "WWV 2.5 MHz"

[[recorder.channels]]
ssrc = 5000000
frequency_hz = 5000000
description = "WWV 5 MHz"

[[recorder.channels]]
ssrc = 10000000
frequency_hz = 10000000
description = "WWV 10 MHz"

[[recorder.channels]]
ssrc = 15000000
frequency_hz = 15000000
description = "WWV 15 MHz"

[[recorder.channels]]
ssrc = 20000000
frequency_hz = 20000000
description = "WWV 20 MHz"

[[recorder.channels]]
ssrc = 25000000
frequency_hz = 25000000
description = "WWV 25 MHz"

[[recorder.channels]]
ssrc = 3330000
frequency_hz = 3330000
description = "CHU 3.33 MHz"

[[recorder.channels]]
ssrc = 7850000
frequency_hz = 7850000
description = "CHU 7.85 MHz"

[[recorder.channels]]
ssrc = 14670000
frequency_hz = 14670000
description = "CHU 14.67 MHz"

# Everything else uses sensible defaults:
# - preset = "iq" (for GRAPE)
# - sample_rate = 16000 Hz
# - processor = "grape"
# - enabled = true
# - compress = true (wavpack)
# - organize by date and frequency
# - process daily at 00:05 UTC
# - upload daily at 00:30 UTC (if configured)

