# GRAPE Recording Configuration for AC0G
# Production configuration for WWV and CHU time signal recording

[station]
callsign = "AC0G"
grid_square = "EM38ww"
id = "AC0G"
instrument_id = "RX888"
description = "GRAPE station with RX888 MkII and ka9q-radio"

[ka9q]
# ka9q-radio status address
status_address = "239.251.200.193"
auto_create_channels = true

[recorder]
# Recording directories
data_dir = "/mnt/grape-data/raw"
archive_dir = "/mnt/grape-data/archive"

# Recording parameters
recording_interval = 60  # 60 second files
continuous = true

# WWV and CHU channels for GRAPE
# All channels use IQ mode for full bandwidth capture

[[recorder.channels]]
ssrc = 2500000
frequency_hz = 2500000
preset = "iq"
sample_rate = 12000
description = "WWV 2.5 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 3330000
frequency_hz = 3330000
preset = "iq"
sample_rate = 12000
description = "CHU 3.33 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 5000000
frequency_hz = 5000000
preset = "iq"
sample_rate = 12000
description = "WWV 5 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 7850000
frequency_hz = 7850000
preset = "iq"
sample_rate = 12000
description = "CHU 7.85 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 10000000
frequency_hz = 10000000
preset = "iq"
sample_rate = 12000
description = "WWV 10 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 14670000
frequency_hz = 14670000
preset = "iq"
sample_rate = 12000
description = "CHU 14.67 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 15000000
frequency_hz = 15000000
preset = "iq"
sample_rate = 12000
description = "WWV 15 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 20000000
frequency_hz = 20000000
preset = "iq"
sample_rate = 12000
description = "WWV 20 MHz"
enabled = true
processor = "grape"

[[recorder.channels]]
ssrc = 25000000
frequency_hz = 25000000
preset = "iq"
sample_rate = 12000
description = "WWV 25 MHz"
enabled = true
processor = "grape"

[processor]
enabled = false  # Enable when ready to test processing

[processor.grape]
# GRAPE processing configuration
process_time = "00:05"
process_timezone = "UTC"
expected_files_per_day = 1440
max_gap_minutes = 5
repair_gaps = true
interpolate_max_minutes = 2
output_sample_rate = 10
output_format = "digital_rf"

[uploader]
enabled = false  # Enable when ready to upload
upload_enabled = false

[logging]
level = "INFO"
console_output = true

[monitoring]
enable_metrics = false

