# Test Configuration for Creating a New Channel
# This tests dynamic channel creation with a frequency that doesn't currently exist
# Based on your existing channels, this creates a channel at 14.5 MHz (between 14.074 and 14.080)

[station]
callsign = "AC0G"
grid_square = "EM38ww"

[ka9q]
status_address = "239.251.200.193"
auto_create_channels = true

[recorder]
data_dir = "/tmp/test-recording"

# Test channel - 14.5 MHz (new frequency not in current channel list)
[[recorder.channels]]
ssrc = 14500000
frequency_hz = 14500000
preset = "usb"
sample_rate = 12000
description = "Test channel 14.5 MHz"
enabled = true

